/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Navigate: typeof import('react-router-dom')['Navigate']
  const React: typeof import('react')['default']
  const useCallback: typeof import('react')['useCallback']
  const useEffect: typeof import('react')['useEffect']
  const useLocation: typeof import('react-router-dom')['useLocation']
  const useMemo: typeof import('react')['useMemo']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
